[versions]
agp = "8.10.1"
kotlin = "2.2.10"
androidx-core = "1.16.0"
androidx-appcompat = "1.7.1"
androidx-activity-compose = "1.10.1"
androidx-viewmodel-compose = "2.9.2"
androidx-navigation-compose = "2.9.0-rc01"
android-minSdk = "28"
android-compileSdk = "36"
app-version-name = "0.0.0"
app-version-code = "1"
namespace = "cz.johnyapps.tictactoe"
java = "17"
koin = "4.0.2"
compose-multiplatfrom = "1.8.2"
skie = "0.10.6"
ktor = "3.2.3"
kotlinx-datetime = "0.7.1"
kotlinx-serialization = "1.9.0"
kotlinx-coroutines = "1.10.2"
datastore = "1.1.4" # Skip 1.1.5, it's broken
detekt = "1.23.8"
detekt-compose = "0.4.27"

[libraries]
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-viewmodel-compose" }
androidx-navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation-compose" }

# Gradle
gradle-android = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
gradle-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-compose = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "compose-multiplatfrom" }
gradle-detekt = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }

# Koin
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }

# Ktor
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-ios = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

# KotlinX
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

# Datastore
datastore-core = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# Detekt
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
detekt-compose = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "detekt-compose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatfrom" }
skie = { id = "co.touchlab.skie", version.ref = "skie" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

local-android-app = { id = "cz.johnyapps.tictactoe.android.app", version = "unspecified" }
local-android-library = { id = "cz.johnyapps.tictactoe.android.library", version = "unspecified" }
local-multiplatform-library = { id = "cz.johnyapps.tictactoe.multiplatform.library", version = "unspecified" }
local-multiplatform-ui = { id = "cz.johnyapps.tictactoe.multiplatform.ui", version = "unspecified" }
local-networking = { id = "cz.johnyapps.tictactoe.networking", version = "unspecified" }
